services:

  api:
    image: denoland/deno:latest
    restart: unless-stopped
    volumes:
      - ./services/api:/app
    ports:
      - 8000:8000
    working_dir: /app
    command: deno task dev

  app-vue:
    image: denoland/deno:latest
    restart: unless-stopped
    depends_on: 
      - api
    volumes:
      - ./services/app-vue:/app
      - ./services/api/types:/types
      - ./services/styleguide-vue/src/components:/ui
    ports:
      - 5173:5173
    working_dir: /app
    environment: 
      SHIPMENTS_UI_PATH: /ui
      SHIPMENTS_TYPES_PATH: /types
      VITE_API_BASE: //localhost:8000
    command: deno task dev

  styleguide-vue:
    build: ./services/styleguide-vue
    restart: unless-stopped
    volumes:
      - ./services/styleguide-vue:/app
      - /app/node_modules
    ports:
      - 6006:6006
    working_dir: /app
    command: npm run storybook

  styleguide-vue-test-watch:
    build:
      context: ./services/styleguide-vue
      dockerfile: Dockerfile
    volumes:
      - ./services/styleguide-vue:/app
      - /app/node_modules
    command: npx vitest --browser.headless -u
    tty: true
    stdin_open: true
